apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: huminex-platform-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OriginXLabs-Org/HUMINEX.git
    targetRevision: main
    path: infra/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: huminex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
